### ISSUE TITLE
Evaluate TAP Service

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1426]
O objetivo é testar os limites da ferramenta e identificar os principais requisitos necessários para o ambiente de produção.

- [x] testar as consultas que serão usadas no curso
- [x] testar o serviço com o uso de consultas 'pesadas'
- [x] verificar o tempo de execução limite de uma consulta
- [x] testar o serviço tap com o Topcat e o Astroquery
- [ ] testar o serviço tap com a biblioteca Astroquery via Jupyter Notebook
- [x] documentar os tipos de consultas científicas e o seus resultados (volume, time, número de linhas etc)
```[tasklist]
### Tasks
```
