### ISSUE TITLE
Create HIPS images for DES DR2

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1428]
Rodar para o DES DR2 completos (5000 graus quadrados)

- [x] rodar para as bandas r, g, i 
- [x] validar resultados banda r 
- [x] validar resultados banda g 
- [x] validar resultados banda i 
- [x] gerar as RGBs 
- [x] report com tempos de execução 
```[tasklist]
### Tasks
- [x] Checar imagens faltantes nas bandas e nos NSides (locais vazios e cores estranhas).
- [x] Colocar as imagens criadas no ambiente DEV para visualização com mais funcionalidades. (ticket aberto https://ticket.linea.org.br/ticket/14317)
```

**Comment by gschwend** [comment]
@crisingulani adicionei o @adrianopieres nesse issue já que ele está ajudando na investigação do pixels faltantes/diferenças nos sistemas de coordenadas ou na projeção.

**Comment by crisingulani** [comment]
Tempo de execução para o Y6 FULL

Os resultados estão em: /lustre/t1/tmp/singulani/hipsimage/outputs/

```
band r    : 24h       parallel
band g    : 15h       parallel
band i    : 1d 3h     parallel
RGB       : 8h	
```	

Os RGBs estão em: /lustre/t1/tmp/singulani/hipsimage/outputs/hips_rgb

**Comment by crisingulani** [comment]
mais informações em: https://docs.google.com/document/d/1yn-Uuax0VCVMxA4PsGHCwaoY43Dz-BIj6wrUUEXLGUQ/edit
