### ISSUE TITLE
Autenticação LIneA  SAML

### ISSUE THREAD

**Issue by glaubervila** [linea-it/dri#1510]
Substituir a autenticação federada que atualmente utiliza Django Shibboleth pela Django Saml 2

```[tasklist]
### Tasks
- [ ] https://github.com/linea-it/dri/issues/1511
- [x] Remover a atutenticação com Shibboleth e atualizar documentação.
- [x] Instalar Django Saml2
- [ ] Configurar a autenticação no ambiente dev
- [ ] Configurar a autenticação no ambiente prod.
- [ ] Atualizar documentação
```

**Comment by gschwend** [comment]
FYI: os itens faltantes serão cobertos em outros cards
