### ISSUE TITLE
final minor adjustments

### ISSUE THREAD

**Issue by gschwend** [linea-it/dri#1566]
```[tasklist]
### Tasks
- [x] Return title and subtitle to NCSA's version (adding number 2 to data release) (see screenshot below)
- [x] remove parenthesis from all links
- [x] remove the link of the expression "video tutorials" on ABOUT page
```

![Image](https://github.com/user-attachments/assets/bffb2478-a9fb-427e-af78-de2dbd65229d)
